package com.linjia.web.query;

import java.util.Date;

import com.linjia.base.query.Query;

public class BrandQuery extends Query{
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_brand.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_brand.name
     *
     * @mbggenerated
     */
    private String name;
    
    /** 查询专用* */
    private String nameQuery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_brand.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_brand.logo_path
     *
     * @mbggenerated
     */
    private String logoPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_brand.cre_date
     *
     * @mbggenerated
     */
    private Date creDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_brand.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_brand.id
     *
     * @return the value of b_brand.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_brand.id
     *
     * @param id the value for b_brand.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_brand.name
     *
     * @return the value of b_brand.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_brand.name
     *
     * @param name the value for b_brand.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_brand.description
     *
     * @return the value of b_brand.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_brand.description
     *
     * @param description the value for b_brand.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_brand.logo_path
     *
     * @return the value of b_brand.logo_path
     *
     * @mbggenerated
     */
    public String getLogoPath() {
        return logoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_brand.logo_path
     *
     * @param logoPath the value for b_brand.logo_path
     *
     * @mbggenerated
     */
    public void setLogoPath(String logoPath) {
        this.logoPath = logoPath == null ? null : logoPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_brand.cre_date
     *
     * @return the value of b_brand.cre_date
     *
     * @mbggenerated
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_brand.cre_date
     *
     * @param creDate the value for b_brand.cre_date
     *
     * @mbggenerated
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_brand.deleted
     *
     * @return the value of b_brand.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_brand.deleted
     *
     * @param deleted the value for b_brand.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

	public String getNameQuery() {
		return nameQuery;
	}

	public void setNameQuery(String nameQuery) {
		this.nameQuery = nameQuery;
	}
    
    
}