package com.linjia.web.query;

import java.math.BigDecimal;

import com.linjia.base.query.Query;

public class MallMasterQuery extends Query{
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.mall_name
     *
     * @mbggenerated
     */
    private String mallName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.mall_code
     *
     * @mbggenerated
     */
    private String mallCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.mall_type
     *
     * @mbggenerated
     */
    private Integer mallType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.province_id
     *
     * @mbggenerated
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.province_name
     *
     * @mbggenerated
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.city_id
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.city_name
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.county_id
     *
     * @mbggenerated
     */
    private Integer countyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.county_name
     *
     * @mbggenerated
     */
    private String countyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.logo
     *
     * @mbggenerated
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.latitude
     *
     * @mbggenerated
     */
    private BigDecimal latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.longitude
     *
     * @mbggenerated
     */
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.mention
     *
     * @mbggenerated
     */
    private Integer mention;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.is_send
     *
     * @mbggenerated
     */
    private Integer isSend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.send_distance
     *
     * @mbggenerated
     */
    private BigDecimal sendDistance;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.send_distance
     *
     * @mbggenerated
     */
    private BigDecimal sendPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.send_limit_money
     *
     * @mbggenerated
     */
    private BigDecimal sendLimitMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.send_limit_points
     *
     * @mbggenerated
     */
    private Integer sendLimitPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.is_support_third_deliver
     *
     * @mbggenerated
     */
    private Integer isSupportThirdDeliver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.is_support_self_deliver
     *
     * @mbggenerated
     */
    private Integer isSupportSelfDeliver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.useFlg
     *
     * @mbggenerated
     */
    private Integer useflg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.mallareaID
     *
     * @mbggenerated
     */
    private Integer mallareaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_master.external_no
     *
     * @mbggenerated
     */
    private String externalNo;
    
  //配送方式(多个以逗号隔开，设为默认的放在最前面)
    private String send_type;
    //配送日期
    private String send_time;
   // 配送时间
    private String send_hour;
   // 自提日期
    private String getbyself_time;
    //自提时间
    private String getbyself_hour;
    
    //店铺标签(多个以逗号隔开，0.自提；2配送)
    private String shop_label;

    //门店营业状态
    private Integer mallStatus;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.id
     *
     * @return the value of b_mall_master.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.id
     *
     * @param id the value for b_mall_master.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.mall_name
     *
     * @return the value of b_mall_master.mall_name
     *
     * @mbggenerated
     */
    public String getMallName() {
        return mallName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.mall_name
     *
     * @param mallName the value for b_mall_master.mall_name
     *
     * @mbggenerated
     */
    public void setMallName(String mallName) {
        this.mallName = mallName == null ? null : mallName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.mall_code
     *
     * @return the value of b_mall_master.mall_code
     *
     * @mbggenerated
     */
    public String getMallCode() {
        return mallCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.mall_code
     *
     * @param mallCode the value for b_mall_master.mall_code
     *
     * @mbggenerated
     */
    public void setMallCode(String mallCode) {
        this.mallCode = mallCode == null ? null : mallCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.mall_type
     *
     * @return the value of b_mall_master.mall_type
     *
     * @mbggenerated
     */
    public Integer getMallType() {
        return mallType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.mall_type
     *
     * @param mallType the value for b_mall_master.mall_type
     *
     * @mbggenerated
     */
    public void setMallType(Integer mallType) {
        this.mallType = mallType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.province_id
     *
     * @return the value of b_mall_master.province_id
     *
     * @mbggenerated
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.province_id
     *
     * @param provinceId the value for b_mall_master.province_id
     *
     * @mbggenerated
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.province_name
     *
     * @return the value of b_mall_master.province_name
     *
     * @mbggenerated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.province_name
     *
     * @param provinceName the value for b_mall_master.province_name
     *
     * @mbggenerated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.city_id
     *
     * @return the value of b_mall_master.city_id
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.city_id
     *
     * @param cityId the value for b_mall_master.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.city_name
     *
     * @return the value of b_mall_master.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.city_name
     *
     * @param cityName the value for b_mall_master.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.county_id
     *
     * @return the value of b_mall_master.county_id
     *
     * @mbggenerated
     */
    public Integer getCountyId() {
        return countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.county_id
     *
     * @param countyId the value for b_mall_master.county_id
     *
     * @mbggenerated
     */
    public void setCountyId(Integer countyId) {
        this.countyId = countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.county_name
     *
     * @return the value of b_mall_master.county_name
     *
     * @mbggenerated
     */
    public String getCountyName() {
        return countyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.county_name
     *
     * @param countyName the value for b_mall_master.county_name
     *
     * @mbggenerated
     */
    public void setCountyName(String countyName) {
        this.countyName = countyName == null ? null : countyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.address
     *
     * @return the value of b_mall_master.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.address
     *
     * @param address the value for b_mall_master.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.logo
     *
     * @return the value of b_mall_master.logo
     *
     * @mbggenerated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.logo
     *
     * @param logo the value for b_mall_master.logo
     *
     * @mbggenerated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.phone
     *
     * @return the value of b_mall_master.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.phone
     *
     * @param phone the value for b_mall_master.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.mobile
     *
     * @return the value of b_mall_master.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.mobile
     *
     * @param mobile the value for b_mall_master.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.description
     *
     * @return the value of b_mall_master.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.description
     *
     * @param description the value for b_mall_master.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.latitude
     *
     * @return the value of b_mall_master.latitude
     *
     * @mbggenerated
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.latitude
     *
     * @param latitude the value for b_mall_master.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.longitude
     *
     * @return the value of b_mall_master.longitude
     *
     * @mbggenerated
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.longitude
     *
     * @param longitude the value for b_mall_master.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.mention
     *
     * @return the value of b_mall_master.mention
     *
     * @mbggenerated
     */
    public Integer getMention() {
        return mention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.mention
     *
     * @param mention the value for b_mall_master.mention
     *
     * @mbggenerated
     */
    public void setMention(Integer mention) {
        this.mention = mention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.is_send
     *
     * @return the value of b_mall_master.is_send
     *
     * @mbggenerated
     */
    public Integer getIsSend() {
        return isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.is_send
     *
     * @param isSend the value for b_mall_master.is_send
     *
     * @mbggenerated
     */
    public void setIsSend(Integer isSend) {
        this.isSend = isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.send_distance
     *
     * @return the value of b_mall_master.send_distance
     *
     * @mbggenerated
     */
    public BigDecimal getSendDistance() {
        return sendDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.send_distance
     *
     * @param sendDistance the value for b_mall_master.send_distance
     *
     * @mbggenerated
     */
    public void setSendDistance(BigDecimal sendDistance) {
        this.sendDistance = sendDistance;
    }

    
    
    public BigDecimal getSendPrice() {
		return sendPrice;
	}

	public void setSendPrice(BigDecimal sendPrice) {
		this.sendPrice = sendPrice;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.send_limit_money
     *
     * @return the value of b_mall_master.send_limit_money
     *
     * @mbggenerated
     */
    public BigDecimal getSendLimitMoney() {
        return sendLimitMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.send_limit_money
     *
     * @param sendLimitMoney the value for b_mall_master.send_limit_money
     *
     * @mbggenerated
     */
    public void setSendLimitMoney(BigDecimal sendLimitMoney) {
        this.sendLimitMoney = sendLimitMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.send_limit_points
     *
     * @return the value of b_mall_master.send_limit_points
     *
     * @mbggenerated
     */
    public Integer getSendLimitPoints() {
        return sendLimitPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.send_limit_points
     *
     * @param sendLimitPoints the value for b_mall_master.send_limit_points
     *
     * @mbggenerated
     */
    public void setSendLimitPoints(Integer sendLimitPoints) {
        this.sendLimitPoints = sendLimitPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.is_support_third_deliver
     *
     * @return the value of b_mall_master.is_support_third_deliver
     *
     * @mbggenerated
     */
    public Integer getIsSupportThirdDeliver() {
        return isSupportThirdDeliver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.is_support_third_deliver
     *
     * @param isSupportThirdDeliver the value for b_mall_master.is_support_third_deliver
     *
     * @mbggenerated
     */
    public void setIsSupportThirdDeliver(Integer isSupportThirdDeliver) {
        this.isSupportThirdDeliver = isSupportThirdDeliver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.is_support_self_deliver
     *
     * @return the value of b_mall_master.is_support_self_deliver
     *
     * @mbggenerated
     */
    public Integer getIsSupportSelfDeliver() {
        return isSupportSelfDeliver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.is_support_self_deliver
     *
     * @param isSupportSelfDeliver the value for b_mall_master.is_support_self_deliver
     *
     * @mbggenerated
     */
    public void setIsSupportSelfDeliver(Integer isSupportSelfDeliver) {
        this.isSupportSelfDeliver = isSupportSelfDeliver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.useFlg
     *
     * @return the value of b_mall_master.useFlg
     *
     * @mbggenerated
     */
    public Integer getUseflg() {
        return useflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.useFlg
     *
     * @param useflg the value for b_mall_master.useFlg
     *
     * @mbggenerated
     */
    public void setUseflg(Integer useflg) {
        this.useflg = useflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.mallareaID
     *
     * @return the value of b_mall_master.mallareaID
     *
     * @mbggenerated
     */
    public Integer getMallareaid() {
        return mallareaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.mallareaID
     *
     * @param mallareaid the value for b_mall_master.mallareaID
     *
     * @mbggenerated
     */
    public void setMallareaid(Integer mallareaid) {
        this.mallareaid = mallareaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_master.external_no
     *
     * @return the value of b_mall_master.external_no
     *
     * @mbggenerated
     */
    public String getExternalNo() {
        return externalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_master.external_no
     *
     * @param externalNo the value for b_mall_master.external_no
     *
     * @mbggenerated
     */
    public void setExternalNo(String externalNo) {
        this.externalNo = externalNo == null ? null : externalNo.trim();
    }

	public String getSend_type() {
		return send_type;
	}

	public void setSend_type(String send_type) {
		this.send_type = send_type;
	}

	public String getSend_time() {
		return send_time;
	}

	public void setSend_time(String send_time) {
		this.send_time = send_time;
	}

	public String getSend_hour() {
		return send_hour;
	}

	public void setSend_hour(String send_hour) {
		this.send_hour = send_hour;
	}

	public String getGetbyself_time() {
		return getbyself_time;
	}

	public void setGetbyself_time(String getbyself_time) {
		this.getbyself_time = getbyself_time;
	}

	public String getGetbyself_hour() {
		return getbyself_hour;
	}

	public void setGetbyself_hour(String getbyself_hour) {
		this.getbyself_hour = getbyself_hour;
	}

	public String getShop_label() {
		return shop_label;
	}

	public void setShop_label(String shop_label) {
		this.shop_label = shop_label;
	}

	public Integer getMallStatus() {
		return mallStatus;
	}

	public void setMallStatus(Integer mallStatus) {
		this.mallStatus = mallStatus;
	}
    
    
}