package com.linjia.web.query;

import java.util.Date;

import com.linjia.base.query.Query;

public class NoticeManagerQuery extends Query{
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_notice_manager.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_notice_manager.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_notice_manager.creator_id
     *
     * @mbggenerated
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_notice_manager.cre_date
     *
     * @mbggenerated
     */
    private Date creDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_notice_manager.use_status
     *
     * @mbggenerated
     */
    private Boolean useStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_notice_manager.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_notice_manager.id
     *
     * @return the value of b_notice_manager.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_notice_manager.id
     *
     * @param id the value for b_notice_manager.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_notice_manager.content
     *
     * @return the value of b_notice_manager.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_notice_manager.content
     *
     * @param content the value for b_notice_manager.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_notice_manager.creator_id
     *
     * @return the value of b_notice_manager.creator_id
     *
     * @mbggenerated
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_notice_manager.creator_id
     *
     * @param creatorId the value for b_notice_manager.creator_id
     *
     * @mbggenerated
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_notice_manager.cre_date
     *
     * @return the value of b_notice_manager.cre_date
     *
     * @mbggenerated
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_notice_manager.cre_date
     *
     * @param creDate the value for b_notice_manager.cre_date
     *
     * @mbggenerated
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_notice_manager.use_status
     *
     * @return the value of b_notice_manager.use_status
     *
     * @mbggenerated
     */
    public Boolean getUseStatus() {
        return useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_notice_manager.use_status
     *
     * @param useStatus the value for b_notice_manager.use_status
     *
     * @mbggenerated
     */
    public void setUseStatus(Boolean useStatus) {
        this.useStatus = useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_notice_manager.deleted
     *
     * @return the value of b_notice_manager.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_notice_manager.deleted
     *
     * @param deleted the value for b_notice_manager.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
    
    
}