package com.linjia.web.query;

import java.math.BigDecimal;
import java.util.Date;

import com.linjia.base.query.Query;

public class ScoreProductQuery extends Query{
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.p_code
     *
     * @mbggenerated
     */
    private String pCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.old_price
     *
     * @mbggenerated
     */
    private BigDecimal oldPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.image_path
     *
     * @mbggenerated
     */
    private String imagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.detail_path
     *
     * @mbggenerated
     */
    private String detailPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.hidden_info
     *
     * @mbggenerated
     */
    private String hiddenInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.cre_date
     *
     * @mbggenerated
     */
    private Date creDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.id
     *
     * @return the value of b_score_product.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.id
     *
     * @param id the value for b_score_product.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.p_code
     *
     * @return the value of b_score_product.p_code
     *
     * @mbggenerated
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.p_code
     *
     * @param pCode the value for b_score_product.p_code
     *
     * @mbggenerated
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.product_id
     *
     * @return the value of b_score_product.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.product_id
     *
     * @param productId the value for b_score_product.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.type
     *
     * @return the value of b_score_product.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.type
     *
     * @param type the value for b_score_product.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.name
     *
     * @return the value of b_score_product.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.name
     *
     * @param name the value for b_score_product.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.price
     *
     * @return the value of b_score_product.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.price
     *
     * @param price the value for b_score_product.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.old_price
     *
     * @return the value of b_score_product.old_price
     *
     * @mbggenerated
     */
    public BigDecimal getOldPrice() {
        return oldPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.old_price
     *
     * @param oldPrice the value for b_score_product.old_price
     *
     * @mbggenerated
     */
    public void setOldPrice(BigDecimal oldPrice) {
        this.oldPrice = oldPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.score
     *
     * @return the value of b_score_product.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.score
     *
     * @param score the value for b_score_product.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.image_path
     *
     * @return the value of b_score_product.image_path
     *
     * @mbggenerated
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.image_path
     *
     * @param imagePath the value for b_score_product.image_path
     *
     * @mbggenerated
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.detail_path
     *
     * @return the value of b_score_product.detail_path
     *
     * @mbggenerated
     */
    public String getDetailPath() {
        return detailPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.detail_path
     *
     * @param detailPath the value for b_score_product.detail_path
     *
     * @mbggenerated
     */
    public void setDetailPath(String detailPath) {
        this.detailPath = detailPath == null ? null : detailPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.hidden_info
     *
     * @return the value of b_score_product.hidden_info
     *
     * @mbggenerated
     */
    public String getHiddenInfo() {
        return hiddenInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.hidden_info
     *
     * @param hiddenInfo the value for b_score_product.hidden_info
     *
     * @mbggenerated
     */
    public void setHiddenInfo(String hiddenInfo) {
        this.hiddenInfo = hiddenInfo == null ? null : hiddenInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.quantity
     *
     * @return the value of b_score_product.quantity
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.quantity
     *
     * @param quantity the value for b_score_product.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.cre_date
     *
     * @return the value of b_score_product.cre_date
     *
     * @mbggenerated
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.cre_date
     *
     * @param creDate the value for b_score_product.cre_date
     *
     * @mbggenerated
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.deleted
     *
     * @return the value of b_score_product.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.deleted
     *
     * @param deleted the value for b_score_product.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
    
    private String creDateStart;
    private String creDateEnd;
	private Boolean useStatus;
	private String nameQuery;

	public Boolean getUseStatus() {
		return useStatus;
	}

	public void setUseStatus(Boolean useStatus) {
		this.useStatus = useStatus;
	}

	public String getCreDateStart() {
		return creDateStart;
	}

	public void setCreDateStart(String creDateStart) {
		this.creDateStart = creDateStart;
	}

	public String getCreDateEnd() {
		return creDateEnd;
	}

	public void setCreDateEnd(String creDateEnd) {
		this.creDateEnd = creDateEnd;
	}

	public String getNameQuery() {
		return nameQuery;
	}

	public void setNameQuery(String nameQuery) {
		this.nameQuery = nameQuery;
	}
    
}