package com.linjia.web.model;

import java.util.Date;

public class ActivityMemberPromotion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_member_promotion.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_member_promotion.activity_type
     *
     * @mbggenerated
     */
    private Integer activityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_member_promotion.activity_name
     *
     * @mbggenerated
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_member_promotion.start_time
     *
     * @mbggenerated
     */
    private Date startTime;
    private String startTimeStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_member_promotion.end_time
     *
     * @mbggenerated
     */
    private Date endTime;
    private String endTimeStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_member_promotion.prize_type
     *
     * @mbggenerated
     */
    private Integer prizeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_member_promotion.prize_name
     *
     * @mbggenerated
     */
    private String prizeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_member_promotion.prize_num
     *
     * @mbggenerated
     */
    private Integer prizeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_member_promotion.card_coupon_id
     *
     * @mbggenerated
     */
    private Long cardCouponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_member_promotion.sort_index
     *
     * @mbggenerated
     */
    private Integer sortIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_member_promotion.use_status
     *
     * @mbggenerated
     */
    private Boolean useStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_member_promotion.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_member_promotion.id
     *
     * @return the value of b_activity_member_promotion.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_member_promotion.id
     *
     * @param id the value for b_activity_member_promotion.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_member_promotion.activity_type
     *
     * @return the value of b_activity_member_promotion.activity_type
     *
     * @mbggenerated
     */
    public Integer getActivityType() {
        return activityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_member_promotion.activity_type
     *
     * @param activityType the value for b_activity_member_promotion.activity_type
     *
     * @mbggenerated
     */
    public void setActivityType(Integer activityType) {
        this.activityType = activityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_member_promotion.activity_name
     *
     * @return the value of b_activity_member_promotion.activity_name
     *
     * @mbggenerated
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_member_promotion.activity_name
     *
     * @param activityName the value for b_activity_member_promotion.activity_name
     *
     * @mbggenerated
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_member_promotion.start_time
     *
     * @return the value of b_activity_member_promotion.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_member_promotion.start_time
     *
     * @param startTime the value for b_activity_member_promotion.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_member_promotion.end_time
     *
     * @return the value of b_activity_member_promotion.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_member_promotion.end_time
     *
     * @param endTime the value for b_activity_member_promotion.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_member_promotion.prize_type
     *
     * @return the value of b_activity_member_promotion.prize_type
     *
     * @mbggenerated
     */
    public Integer getPrizeType() {
        return prizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_member_promotion.prize_type
     *
     * @param prizeType the value for b_activity_member_promotion.prize_type
     *
     * @mbggenerated
     */
    public void setPrizeType(Integer prizeType) {
        this.prizeType = prizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_member_promotion.prize_name
     *
     * @return the value of b_activity_member_promotion.prize_name
     *
     * @mbggenerated
     */
    public String getPrizeName() {
        return prizeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_member_promotion.prize_name
     *
     * @param prizeName the value for b_activity_member_promotion.prize_name
     *
     * @mbggenerated
     */
    public void setPrizeName(String prizeName) {
        this.prizeName = prizeName == null ? null : prizeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_member_promotion.prize_num
     *
     * @return the value of b_activity_member_promotion.prize_num
     *
     * @mbggenerated
     */
    public Integer getPrizeNum() {
        return prizeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_member_promotion.prize_num
     *
     * @param prizeNum the value for b_activity_member_promotion.prize_num
     *
     * @mbggenerated
     */
    public void setPrizeNum(Integer prizeNum) {
        this.prizeNum = prizeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_member_promotion.card_coupon_id
     *
     * @return the value of b_activity_member_promotion.card_coupon_id
     *
     * @mbggenerated
     */
    public Long getCardCouponId() {
        return cardCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_member_promotion.card_coupon_id
     *
     * @param cardCouponId the value for b_activity_member_promotion.card_coupon_id
     *
     * @mbggenerated
     */
    public void setCardCouponId(Long cardCouponId) {
        this.cardCouponId = cardCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_member_promotion.sort_index
     *
     * @return the value of b_activity_member_promotion.sort_index
     *
     * @mbggenerated
     */
    public Integer getSortIndex() {
        return sortIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_member_promotion.sort_index
     *
     * @param sortIndex the value for b_activity_member_promotion.sort_index
     *
     * @mbggenerated
     */
    public void setSortIndex(Integer sortIndex) {
        this.sortIndex = sortIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_member_promotion.use_status
     *
     * @return the value of b_activity_member_promotion.use_status
     *
     * @mbggenerated
     */
    public Boolean getUseStatus() {
        return useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_member_promotion.use_status
     *
     * @param useStatus the value for b_activity_member_promotion.use_status
     *
     * @mbggenerated
     */
    public void setUseStatus(Boolean useStatus) {
        this.useStatus = useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_member_promotion.deleted
     *
     * @return the value of b_activity_member_promotion.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_member_promotion.deleted
     *
     * @param deleted the value for b_activity_member_promotion.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
    
    private Date creDate;

	public Date getCreDate() {
		return creDate;
	}

	public void setCreDate(Date creDate) {
		this.creDate = creDate;
	}

	public String getStartTimeStr() {
		return startTimeStr;
	}

	public void setStartTimeStr(String startTimeStr) {
		this.startTimeStr = startTimeStr;
	}

	public String getEndTimeStr() {
		return endTimeStr;
	}

	public void setEndTimeStr(String endTimeStr) {
		this.endTimeStr = endTimeStr;
	}

    
    
}