package com.linjia.web.model;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.web.multipart.MultipartFile;

public class ActivityPrepare {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_prepare.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_prepare.activity_start_time
     *
     * @mbggenerated
     */
    private Date activityStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_prepare.activity_end_time
     *
     * @mbggenerated
     */
    private Date activityEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_prepare.getself_start_time
     *
     * @mbggenerated
     */
    private Date getselfStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_prepare.getself_end_time
     *
     * @mbggenerated
     */
    private Date getselfEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_prepare.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_prepare.p_code
     *
     * @mbggenerated
     */
    private String pCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_prepare.p_name
     *
     * @mbggenerated
     */
    private String pName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_prepare.market_price
     *
     * @mbggenerated
     */
    private BigDecimal marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_prepare.activity_price
     *
     * @mbggenerated
     */
    private BigDecimal activityPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_prepare.activity_quantity
     *
     * @mbggenerated
     */
    private Integer activityQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_prepare.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_prepare.image_path
     *
     * @mbggenerated
     */
    private String imagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_prepare.sort_index
     *
     * @mbggenerated
     */
    private Integer sortIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_prepare.activity_status
     *
     * @mbggenerated
     */
    private Integer activityStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_prepare.cre_date
     *
     * @mbggenerated
     */
    private Date creDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_activity_prepare.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_prepare.id
     *
     * @return the value of b_activity_prepare.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_prepare.id
     *
     * @param id the value for b_activity_prepare.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_prepare.activity_start_time
     *
     * @return the value of b_activity_prepare.activity_start_time
     *
     * @mbggenerated
     */
    public Date getActivityStartTime() {
        return activityStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_prepare.activity_start_time
     *
     * @param activityStartTime the value for b_activity_prepare.activity_start_time
     *
     * @mbggenerated
     */
    public void setActivityStartTime(Date activityStartTime) {
        this.activityStartTime = activityStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_prepare.activity_end_time
     *
     * @return the value of b_activity_prepare.activity_end_time
     *
     * @mbggenerated
     */
    public Date getActivityEndTime() {
        return activityEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_prepare.activity_end_time
     *
     * @param activityEndTime the value for b_activity_prepare.activity_end_time
     *
     * @mbggenerated
     */
    public void setActivityEndTime(Date activityEndTime) {
        this.activityEndTime = activityEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_prepare.getself_start_time
     *
     * @return the value of b_activity_prepare.getself_start_time
     *
     * @mbggenerated
     */
    public Date getGetselfStartTime() {
        return getselfStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_prepare.getself_start_time
     *
     * @param getselfStartTime the value for b_activity_prepare.getself_start_time
     *
     * @mbggenerated
     */
    public void setGetselfStartTime(Date getselfStartTime) {
        this.getselfStartTime = getselfStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_prepare.getself_end_time
     *
     * @return the value of b_activity_prepare.getself_end_time
     *
     * @mbggenerated
     */
    public Date getGetselfEndTime() {
        return getselfEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_prepare.getself_end_time
     *
     * @param getselfEndTime the value for b_activity_prepare.getself_end_time
     *
     * @mbggenerated
     */
    public void setGetselfEndTime(Date getselfEndTime) {
        this.getselfEndTime = getselfEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_prepare.product_id
     *
     * @return the value of b_activity_prepare.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_prepare.product_id
     *
     * @param productId the value for b_activity_prepare.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_prepare.p_code
     *
     * @return the value of b_activity_prepare.p_code
     *
     * @mbggenerated
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_prepare.p_code
     *
     * @param pCode the value for b_activity_prepare.p_code
     *
     * @mbggenerated
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_prepare.p_name
     *
     * @return the value of b_activity_prepare.p_name
     *
     * @mbggenerated
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_prepare.p_name
     *
     * @param pName the value for b_activity_prepare.p_name
     *
     * @mbggenerated
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_prepare.market_price
     *
     * @return the value of b_activity_prepare.market_price
     *
     * @mbggenerated
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_prepare.market_price
     *
     * @param marketPrice the value for b_activity_prepare.market_price
     *
     * @mbggenerated
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_prepare.activity_price
     *
     * @return the value of b_activity_prepare.activity_price
     *
     * @mbggenerated
     */
    public BigDecimal getActivityPrice() {
        return activityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_prepare.activity_price
     *
     * @param activityPrice the value for b_activity_prepare.activity_price
     *
     * @mbggenerated
     */
    public void setActivityPrice(BigDecimal activityPrice) {
        this.activityPrice = activityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_prepare.activity_quantity
     *
     * @return the value of b_activity_prepare.activity_quantity
     *
     * @mbggenerated
     */
    public Integer getActivityQuantity() {
        return activityQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_prepare.activity_quantity
     *
     * @param activityQuantity the value for b_activity_prepare.activity_quantity
     *
     * @mbggenerated
     */
    public void setActivityQuantity(Integer activityQuantity) {
        this.activityQuantity = activityQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_prepare.description
     *
     * @return the value of b_activity_prepare.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_prepare.description
     *
     * @param description the value for b_activity_prepare.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_prepare.image_path
     *
     * @return the value of b_activity_prepare.image_path
     *
     * @mbggenerated
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_prepare.image_path
     *
     * @param imagePath the value for b_activity_prepare.image_path
     *
     * @mbggenerated
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_prepare.cre_date
     *
     * @return the value of b_activity_prepare.cre_date
     *
     * @mbggenerated
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_prepare.cre_date
     *
     * @param creDate the value for b_activity_prepare.cre_date
     *
     * @mbggenerated
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_activity_prepare.update_date
     *
     * @return the value of b_activity_prepare.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_activity_prepare.update_date
     *
     * @param updateDate the value for b_activity_prepare.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

	public Integer getSortIndex() {
		return sortIndex;
	}

	public void setSortIndex(Integer sortIndex) {
		this.sortIndex = sortIndex;
	}

	public Integer getActivityStatus() {
		return activityStatus;
	}

	public void setActivityStatus(Integer activityStatus) {
		this.activityStatus = activityStatus;
	}
    
	private String activityEndTimeStr;
	private String activityStartTimeStr;
	private String getselfStartTimeStr;
    private String getselfEndTimeStr;

	/** 商品发货类型：0及时送；1次日达* */
	private Integer pSendType;
	
	/** 提货时间类型：1静态区间；2 N天之后* */
	private Integer gettimeType;
	
	/** 提货时间类型N天之后* */
	private Integer numDaysLater;
	
	private MultipartFile uploadImage;

	public String getActivityEndTimeStr() {
		return activityEndTimeStr;
	}

	public void setActivityEndTimeStr(String activityEndTimeStr) {
		this.activityEndTimeStr = activityEndTimeStr;
	}

	public String getActivityStartTimeStr() {
		return activityStartTimeStr;
	}

	public void setActivityStartTimeStr(String activityStartTimeStr) {
		this.activityStartTimeStr = activityStartTimeStr;
	}

	public String getGetselfStartTimeStr() {
		return getselfStartTimeStr;
	}

	public void setGetselfStartTimeStr(String getselfStartTimeStr) {
		this.getselfStartTimeStr = getselfStartTimeStr;
	}

	public String getGetselfEndTimeStr() {
		return getselfEndTimeStr;
	}

	public void setGetselfEndTimeStr(String getselfEndTimeStr) {
		this.getselfEndTimeStr = getselfEndTimeStr;
	}

	public Integer getpSendType() {
		return pSendType;
	}

	public void setpSendType(Integer pSendType) {
		this.pSendType = pSendType;
	}

	public Integer getGettimeType() {
		return gettimeType;
	}

	public void setGettimeType(Integer gettimeType) {
		this.gettimeType = gettimeType;
	}

	public Integer getNumDaysLater() {
		return numDaysLater;
	}

	public void setNumDaysLater(Integer numDaysLater) {
		this.numDaysLater = numDaysLater;
	}

	public MultipartFile getUploadImage() {
		return uploadImage;
	}

	public void setUploadImage(MultipartFile uploadImage) {
		this.uploadImage = uploadImage;
	}
	
	
    
}