package com.linjia.web.model;

public class AdmissionInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admission_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admission_info.college_id
     *
     * @mbggenerated
     */
    private Integer collegeId;
    private String collegeName;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admission_info.specialty_id
     *
     * @mbggenerated
     */
    private Integer specialtyId;
    private String specialtyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admission_info.batch_id
     *
     * @mbggenerated
     */
    private Integer batchId;
    private String batchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admission_info.year
     *
     * @mbggenerated
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admission_info.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admission_info.admission_num
     *
     * @mbggenerated
     */
    private Integer admissionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admission_info.high_score
     *
     * @mbggenerated
     */
    private Float highScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admission_info.low_score
     *
     * @mbggenerated
     */
    private Float lowScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admission_info.average_score
     *
     * @mbggenerated
     */
    private Float averageScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admission_info.admission_rule_id
     *
     * @mbggenerated
     */
    private Integer admissionRuleId;
    private String description;

    /**
     * 录取规则类型：0选择已有，1新增
     */
    private Integer ruleTab;

    public Integer getRuleTab() {
        return ruleTab;
    }

    public void setRuleTab(Integer ruleTab) {
        this.ruleTab = ruleTab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admission_info.id
     *
     * @return the value of t_admission_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admission_info.id
     *
     * @param id the value for t_admission_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admission_info.college_id
     *
     * @return the value of t_admission_info.college_id
     *
     * @mbggenerated
     */
    public Integer getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admission_info.college_id
     *
     * @param collegeId the value for t_admission_info.college_id
     *
     * @mbggenerated
     */
    public void setCollegeId(Integer collegeId) {
        this.collegeId = collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admission_info.specialty_id
     *
     * @return the value of t_admission_info.specialty_id
     *
     * @mbggenerated
     */
    public Integer getSpecialtyId() {
        return specialtyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admission_info.specialty_id
     *
     * @param specialtyId the value for t_admission_info.specialty_id
     *
     * @mbggenerated
     */
    public void setSpecialtyId(Integer specialtyId) {
        this.specialtyId = specialtyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admission_info.batch_id
     *
     * @return the value of t_admission_info.batch_id
     *
     * @mbggenerated
     */
    public Integer getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admission_info.batch_id
     *
     * @param batchId the value for t_admission_info.batch_id
     *
     * @mbggenerated
     */
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admission_info.year
     *
     * @return the value of t_admission_info.year
     *
     * @mbggenerated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admission_info.year
     *
     * @param year the value for t_admission_info.year
     *
     * @mbggenerated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admission_info.type
     *
     * @return the value of t_admission_info.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admission_info.type
     *
     * @param type the value for t_admission_info.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admission_info.admission_num
     *
     * @return the value of t_admission_info.admission_num
     *
     * @mbggenerated
     */
    public Integer getAdmissionNum() {
        return admissionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admission_info.admission_num
     *
     * @param admissionNum the value for t_admission_info.admission_num
     *
     * @mbggenerated
     */
    public void setAdmissionNum(Integer admissionNum) {
        this.admissionNum = admissionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admission_info.high_score
     *
     * @return the value of t_admission_info.high_score
     *
     * @mbggenerated
     */
    public Float getHighScore() {
        return highScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admission_info.high_score
     *
     * @param highScore the value for t_admission_info.high_score
     *
     * @mbggenerated
     */
    public void setHighScore(Float highScore) {
        this.highScore = highScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admission_info.low_score
     *
     * @return the value of t_admission_info.low_score
     *
     * @mbggenerated
     */
    public Float getLowScore() {
        return lowScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admission_info.low_score
     *
     * @param lowScore the value for t_admission_info.low_score
     *
     * @mbggenerated
     */
    public void setLowScore(Float lowScore) {
        this.lowScore = lowScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admission_info.average_score
     *
     * @return the value of t_admission_info.average_score
     *
     * @mbggenerated
     */
    public Float getAverageScore() {
        return averageScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admission_info.average_score
     *
     * @param averageScore the value for t_admission_info.average_score
     *
     * @mbggenerated
     */
    public void setAverageScore(Float averageScore) {
        this.averageScore = averageScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admission_info.admission_rule_id
     *
     * @return the value of t_admission_info.admission_rule_id
     *
     * @mbggenerated
     */
    public Integer getAdmissionRuleId() {
        return admissionRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admission_info.admission_rule_id
     *
     * @param admissionRuleId the value for t_admission_info.admission_rule_id
     *
     * @mbggenerated
     */
    public void setAdmissionRuleId(Integer admissionRuleId) {
        this.admissionRuleId = admissionRuleId;
    }

    public String getCollegeName() {
        return collegeName;
    }

    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName;
    }

    public String getSpecialtyName() {
        return specialtyName;
    }

    public void setSpecialtyName(String specialtyName) {
        this.specialtyName = specialtyName;
    }

    public String getBatchName() {
        return batchName;
    }

    public void setBatchName(String batchName) {
        this.batchName = batchName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    private Boolean firstRowFlag_college;
    private Integer rowspanNum_college;
    private Boolean firstRowFlag_spceialty;
    private Integer rowspanNum_spceialty;
    private Boolean firstRowFlag_year;
    private Integer rowspanNum_year;
    private Boolean firstRowFlag_batch;
    private Integer rowspanNum_batch;
    private Boolean firstRowFlag_rule;
    private Integer rowspanNum_rule;


    public Boolean getFirstRowFlag_college() {
        return firstRowFlag_college;
    }

    public void setFirstRowFlag_college(Boolean firstRowFlag_college) {
        this.firstRowFlag_college = firstRowFlag_college;
    }

    public Integer getRowspanNum_college() {
        return rowspanNum_college;
    }

    public void setRowspanNum_college(Integer rowspanNum_college) {
        this.rowspanNum_college = rowspanNum_college;
    }

    public Boolean getFirstRowFlag_spceialty() {
        return firstRowFlag_spceialty;
    }

    public void setFirstRowFlag_spceialty(Boolean firstRowFlag_spceialty) {
        this.firstRowFlag_spceialty = firstRowFlag_spceialty;
    }

    public Integer getRowspanNum_spceialty() {
        return rowspanNum_spceialty;
    }

    public void setRowspanNum_spceialty(Integer rowspanNum_spceialty) {
        this.rowspanNum_spceialty = rowspanNum_spceialty;
    }

    public Boolean getFirstRowFlag_year() {
        return firstRowFlag_year;
    }

    public void setFirstRowFlag_year(Boolean firstRowFlag_year) {
        this.firstRowFlag_year = firstRowFlag_year;
    }

    public Integer getRowspanNum_year() {
        return rowspanNum_year;
    }

    public void setRowspanNum_year(Integer rowspanNum_year) {
        this.rowspanNum_year = rowspanNum_year;
    }

    public Boolean getFirstRowFlag_batch() {
        return firstRowFlag_batch;
    }

    public void setFirstRowFlag_batch(Boolean firstRowFlag_batch) {
        this.firstRowFlag_batch = firstRowFlag_batch;
    }

    public Integer getRowspanNum_batch() {
        return rowspanNum_batch;
    }

    public void setRowspanNum_batch(Integer rowspanNum_batch) {
        this.rowspanNum_batch = rowspanNum_batch;
    }

    public Boolean getFirstRowFlag_rule() {
        return firstRowFlag_rule;
    }

    public void setFirstRowFlag_rule(Boolean firstRowFlag_rule) {
        this.firstRowFlag_rule = firstRowFlag_rule;
    }

    public Integer getRowspanNum_rule() {
        return rowspanNum_rule;
    }

    public void setRowspanNum_rule(Integer rowspanNum_rule) {
        this.rowspanNum_rule = rowspanNum_rule;
    }
}