package com.linjia.web.model;

import java.math.BigDecimal;
import java.util.Date;

public class CustMaster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.custID
     *
     * @mbggenerated
     */
    private String custid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.pcustID
     *
     * @mbggenerated
     */
    private Integer pcustid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.custname
     *
     * @mbggenerated
     */
    private String custname;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.custname
     *
     * @mbggenerated
     */
    private String login;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.rankName
     *
     * @mbggenerated
     */
    private String rankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.sumAmt
     *
     * @mbggenerated
     */
    private BigDecimal sumamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.IPPort
     *
     * @mbggenerated
     */
    private String ipport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.lastLogin
     *
     * @mbggenerated
     */
    private Date lastlogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.sexy
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.pwd
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.rankID
     *
     * @mbggenerated
     */
    private Integer rankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.nickName
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.useFlg
     *
     * @mbggenerated
     */
    private Integer useflg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.head_pic
     *
     * @mbggenerated
     */
    private String headPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.custType
     *
     * @mbggenerated
     */
    private Integer custtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.unionName
     *
     * @mbggenerated
     */
    private String unionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.provinceid
     *
     * @mbggenerated
     */
    private Integer provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.provinceName
     *
     * @mbggenerated
     */
    private String provincename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.cityid
     *
     * @mbggenerated
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.cityName
     *
     * @mbggenerated
     */
    private String cityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.countyid
     *
     * @mbggenerated
     */
    private Integer countyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.countyName
     *
     * @mbggenerated
     */
    private String countyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.QQ
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.identityCard
     *
     * @mbggenerated
     */
    private String identitycard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.maritalStatus
     *
     * @mbggenerated
     */
    private String maritalstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.monthlyIncome
     *
     * @mbggenerated
     */
    private Integer monthlyincome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.payPwd
     *
     * @mbggenerated
     */
    private String paypwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.recom_pcustID
     *
     * @mbggenerated
     */
    private Integer recomPcustid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.referee
     *
     * @mbggenerated
     */
    private String referee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.cardNo
     *
     * @mbggenerated
     */
    private String cardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.external_no
     *
     * @mbggenerated
     */
    private String externalNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.register_channel
     *
     * @mbggenerated
     */
    private Integer registerChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.api_customer_rank
     *
     * @mbggenerated
     */
    private String apiCustomerRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.offline_pcustID
     *
     * @mbggenerated
     */
    private String offlinePcustid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.mallID
     *
     * @mbggenerated
     */
    private Integer mallid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_master.offline_pcustID
     *
     * @mbggenerated
     */
    private String appName;
    private String originCode;
    private String orgCode;
    private String orgName;
    
    private Date registerDate;
    
    
    public String getOriginCode() {
		return originCode;
	}

	public void setOriginCode(String originCode) {
		this.originCode = originCode;
	}

	public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getAppName() {
		return appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}

	public Date getRegisterDate() {
		return registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}


	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.user_id
     *
     * @return the value of cust_master.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.user_id
     *
     * @param userId the value for cust_master.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.creator
     *
     * @return the value of cust_master.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.creator
     *
     * @param creator the value for cust_master.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.custID
     *
     * @return the value of cust_master.custID
     *
     * @mbggenerated
     */
    public String getCustid() {
        return custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.custID
     *
     * @param custid the value for cust_master.custID
     *
     * @mbggenerated
     */
    public void setCustid(String custid) {
        this.custid = custid == null ? null : custid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.pcustID
     *
     * @return the value of cust_master.pcustID
     *
     * @mbggenerated
     */
    public Integer getPcustid() {
        return pcustid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.pcustID
     *
     * @param pcustid the value for cust_master.pcustID
     *
     * @mbggenerated
     */
    public void setPcustid(Integer pcustid) {
        this.pcustid = pcustid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.custname
     *
     * @return the value of cust_master.custname
     *
     * @mbggenerated
     */
    public String getCustname() {
        return custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.custname
     *
     * @param custname the value for cust_master.custname
     *
     * @mbggenerated
     */
    public void setCustname(String custname) {
        this.custname = custname == null ? null : custname.trim();
    }

    public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.email
     *
     * @return the value of cust_master.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.email
     *
     * @param email the value for cust_master.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.rankName
     *
     * @return the value of cust_master.rankName
     *
     * @mbggenerated
     */
    public String getRankname() {
        return rankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.rankName
     *
     * @param rankname the value for cust_master.rankName
     *
     * @mbggenerated
     */
    public void setRankname(String rankname) {
        this.rankname = rankname == null ? null : rankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.sumAmt
     *
     * @return the value of cust_master.sumAmt
     *
     * @mbggenerated
     */
    public BigDecimal getSumamt() {
        return sumamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.sumAmt
     *
     * @param sumamt the value for cust_master.sumAmt
     *
     * @mbggenerated
     */
    public void setSumamt(BigDecimal sumamt) {
        this.sumamt = sumamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.IPPort
     *
     * @return the value of cust_master.IPPort
     *
     * @mbggenerated
     */
    public String getIpport() {
        return ipport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.IPPort
     *
     * @param ipport the value for cust_master.IPPort
     *
     * @mbggenerated
     */
    public void setIpport(String ipport) {
        this.ipport = ipport == null ? null : ipport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.lastLogin
     *
     * @return the value of cust_master.lastLogin
     *
     * @mbggenerated
     */
    public Date getLastlogin() {
        return lastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.lastLogin
     *
     * @param lastlogin the value for cust_master.lastLogin
     *
     * @mbggenerated
     */
    public void setLastlogin(Date lastlogin) {
        this.lastlogin = lastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.sexy
     *
     * @return the value of cust_master.sexy
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.sexy
     *
     * @param sexy the value for cust_master.sexy
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.pwd
     *
     * @return the value of cust_master.pwd
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.pwd
     *
     * @param pwd the value for cust_master.pwd
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.rankID
     *
     * @return the value of cust_master.rankID
     *
     * @mbggenerated
     */
    public Integer getRankid() {
        return rankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.rankID
     *
     * @param rankid the value for cust_master.rankID
     *
     * @mbggenerated
     */
    public void setRankid(Integer rankid) {
        this.rankid = rankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.birthday
     *
     * @return the value of cust_master.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.birthday
     *
     * @param birthday the value for cust_master.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.phone
     *
     * @return the value of cust_master.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.phone
     *
     * @param phone the value for cust_master.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.nickName
     *
     * @return the value of cust_master.nickName
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.nickName
     *
     * @param nickname the value for cust_master.nickName
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.useFlg
     *
     * @return the value of cust_master.useFlg
     *
     * @mbggenerated
     */
    public Integer getUseflg() {
        return useflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.useFlg
     *
     * @param useflg the value for cust_master.useFlg
     *
     * @mbggenerated
     */
    public void setUseflg(Integer useflg) {
        this.useflg = useflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.head_pic
     *
     * @return the value of cust_master.head_pic
     *
     * @mbggenerated
     */
    public String getHeadPic() {
        return headPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.head_pic
     *
     * @param headPic the value for cust_master.head_pic
     *
     * @mbggenerated
     */
    public void setHeadPic(String headPic) {
        this.headPic = headPic == null ? null : headPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.custType
     *
     * @return the value of cust_master.custType
     *
     * @mbggenerated
     */
    public Integer getCusttype() {
        return custtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.custType
     *
     * @param custtype the value for cust_master.custType
     *
     * @mbggenerated
     */
    public void setCusttype(Integer custtype) {
        this.custtype = custtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.unionName
     *
     * @return the value of cust_master.unionName
     *
     * @mbggenerated
     */
    public String getUnionname() {
        return unionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.unionName
     *
     * @param unionname the value for cust_master.unionName
     *
     * @mbggenerated
     */
    public void setUnionname(String unionname) {
        this.unionname = unionname == null ? null : unionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.provinceid
     *
     * @return the value of cust_master.provinceid
     *
     * @mbggenerated
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.provinceid
     *
     * @param provinceid the value for cust_master.provinceid
     *
     * @mbggenerated
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.provinceName
     *
     * @return the value of cust_master.provinceName
     *
     * @mbggenerated
     */
    public String getProvincename() {
        return provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.provinceName
     *
     * @param provincename the value for cust_master.provinceName
     *
     * @mbggenerated
     */
    public void setProvincename(String provincename) {
        this.provincename = provincename == null ? null : provincename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.cityid
     *
     * @return the value of cust_master.cityid
     *
     * @mbggenerated
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.cityid
     *
     * @param cityid the value for cust_master.cityid
     *
     * @mbggenerated
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.cityName
     *
     * @return the value of cust_master.cityName
     *
     * @mbggenerated
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.cityName
     *
     * @param cityname the value for cust_master.cityName
     *
     * @mbggenerated
     */
    public void setCityname(String cityname) {
        this.cityname = cityname == null ? null : cityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.countyid
     *
     * @return the value of cust_master.countyid
     *
     * @mbggenerated
     */
    public Integer getCountyid() {
        return countyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.countyid
     *
     * @param countyid the value for cust_master.countyid
     *
     * @mbggenerated
     */
    public void setCountyid(Integer countyid) {
        this.countyid = countyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.countyName
     *
     * @return the value of cust_master.countyName
     *
     * @mbggenerated
     */
    public String getCountyname() {
        return countyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.countyName
     *
     * @param countyname the value for cust_master.countyName
     *
     * @mbggenerated
     */
    public void setCountyname(String countyname) {
        this.countyname = countyname == null ? null : countyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.address
     *
     * @return the value of cust_master.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.address
     *
     * @param address the value for cust_master.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.QQ
     *
     * @return the value of cust_master.QQ
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.QQ
     *
     * @param qq the value for cust_master.QQ
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.identityCard
     *
     * @return the value of cust_master.identityCard
     *
     * @mbggenerated
     */
    public String getIdentitycard() {
        return identitycard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.identityCard
     *
     * @param identitycard the value for cust_master.identityCard
     *
     * @mbggenerated
     */
    public void setIdentitycard(String identitycard) {
        this.identitycard = identitycard == null ? null : identitycard.trim();
    }

  

    public String getMaritalstatus() {
		return maritalstatus;
	}

	public void setMaritalstatus(String maritalstatus) {
		this.maritalstatus = maritalstatus;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.monthlyIncome
     *
     * @return the value of cust_master.monthlyIncome
     *
     * @mbggenerated
     */
    public Integer getMonthlyincome() {
        return monthlyincome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.monthlyIncome
     *
     * @param monthlyincome the value for cust_master.monthlyIncome
     *
     * @mbggenerated
     */
    public void setMonthlyincome(Integer monthlyincome) {
        this.monthlyincome = monthlyincome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.payPwd
     *
     * @return the value of cust_master.payPwd
     *
     * @mbggenerated
     */
    public String getPaypwd() {
        return paypwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.payPwd
     *
     * @param paypwd the value for cust_master.payPwd
     *
     * @mbggenerated
     */
    public void setPaypwd(String paypwd) {
        this.paypwd = paypwd == null ? null : paypwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.recom_pcustID
     *
     * @return the value of cust_master.recom_pcustID
     *
     * @mbggenerated
     */
    public Integer getRecomPcustid() {
        return recomPcustid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.recom_pcustID
     *
     * @param recomPcustid the value for cust_master.recom_pcustID
     *
     * @mbggenerated
     */
    public void setRecomPcustid(Integer recomPcustid) {
        this.recomPcustid = recomPcustid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.referee
     *
     * @return the value of cust_master.referee
     *
     * @mbggenerated
     */
    public String getReferee() {
        return referee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.referee
     *
     * @param referee the value for cust_master.referee
     *
     * @mbggenerated
     */
    public void setReferee(String referee) {
        this.referee = referee == null ? null : referee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.cardNo
     *
     * @return the value of cust_master.cardNo
     *
     * @mbggenerated
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.cardNo
     *
     * @param cardno the value for cust_master.cardNo
     *
     * @mbggenerated
     */
    public void setCardno(String cardno) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.external_no
     *
     * @return the value of cust_master.external_no
     *
     * @mbggenerated
     */
    public String getExternalNo() {
        return externalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.external_no
     *
     * @param externalNo the value for cust_master.external_no
     *
     * @mbggenerated
     */
    public void setExternalNo(String externalNo) {
        this.externalNo = externalNo == null ? null : externalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.register_channel
     *
     * @return the value of cust_master.register_channel
     *
     * @mbggenerated
     */
    public Integer getRegisterChannel() {
        return registerChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.register_channel
     *
     * @param registerChannel the value for cust_master.register_channel
     *
     * @mbggenerated
     */
    public void setRegisterChannel(Integer registerChannel) {
        this.registerChannel = registerChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.api_customer_rank
     *
     * @return the value of cust_master.api_customer_rank
     *
     * @mbggenerated
     */
    public String getApiCustomerRank() {
        return apiCustomerRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.api_customer_rank
     *
     * @param apiCustomerRank the value for cust_master.api_customer_rank
     *
     * @mbggenerated
     */
    public void setApiCustomerRank(String apiCustomerRank) {
        this.apiCustomerRank = apiCustomerRank == null ? null : apiCustomerRank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.offline_pcustID
     *
     * @return the value of cust_master.offline_pcustID
     *
     * @mbggenerated
     */
    public String getOfflinePcustid() {
        return offlinePcustid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.offline_pcustID
     *
     * @param offlinePcustid the value for cust_master.offline_pcustID
     *
     * @mbggenerated
     */
    public void setOfflinePcustid(String offlinePcustid) {
        this.offlinePcustid = offlinePcustid == null ? null : offlinePcustid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_master.mallID
     *
     * @return the value of cust_master.mallID
     *
     * @mbggenerated
     */
    public Integer getMallid() {
        return mallid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_master.mallID
     *
     * @param mallid the value for cust_master.mallID
     *
     * @mbggenerated
     */
    public void setMallid(Integer mallid) {
        this.mallid = mallid;
    }
    
    private int count;
}