package com.linjia.web.model;

import java.math.BigDecimal;

public class MallProductStore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_product_store.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_product_store.mall_id
     *
     * @mbggenerated
     */
    private Integer mallId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_product_store.mall_code
     *
     * @mbggenerated
     */
    private String mallCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_product_store.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_product_store.p_code
     *
     * @mbggenerated
     */
    private String pCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_product_store.market_price
     *
     * @mbggenerated
     */
    private BigDecimal marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_product_store.sale_price
     *
     * @mbggenerated
     */
    private BigDecimal salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_product_store.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_product_store.safe_quantity
     *
     * @mbggenerated
     */
    private Integer safeQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_product_store.online
     *
     * @mbggenerated
     */
    private Boolean online;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_mall_product_store.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_product_store.id
     *
     * @return the value of b_mall_product_store.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_product_store.id
     *
     * @param id the value for b_mall_product_store.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_product_store.mall_id
     *
     * @return the value of b_mall_product_store.mall_id
     *
     * @mbggenerated
     */
    public Integer getMallId() {
        return mallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_product_store.mall_id
     *
     * @param mallId the value for b_mall_product_store.mall_id
     *
     * @mbggenerated
     */
    public void setMallId(Integer mallId) {
        this.mallId = mallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_product_store.mall_code
     *
     * @return the value of b_mall_product_store.mall_code
     *
     * @mbggenerated
     */
    public String getMallCode() {
        return mallCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_product_store.mall_code
     *
     * @param mallCode the value for b_mall_product_store.mall_code
     *
     * @mbggenerated
     */
    public void setMallCode(String mallCode) {
        this.mallCode = mallCode == null ? null : mallCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_product_store.product_id
     *
     * @return the value of b_mall_product_store.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_product_store.product_id
     *
     * @param productId the value for b_mall_product_store.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_product_store.p_code
     *
     * @return the value of b_mall_product_store.p_code
     *
     * @mbggenerated
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_product_store.p_code
     *
     * @param pCode the value for b_mall_product_store.p_code
     *
     * @mbggenerated
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_product_store.market_price
     *
     * @return the value of b_mall_product_store.market_price
     *
     * @mbggenerated
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_product_store.market_price
     *
     * @param marketPrice the value for b_mall_product_store.market_price
     *
     * @mbggenerated
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_product_store.sale_price
     *
     * @return the value of b_mall_product_store.sale_price
     *
     * @mbggenerated
     */
    public BigDecimal getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_product_store.sale_price
     *
     * @param salePrice the value for b_mall_product_store.sale_price
     *
     * @mbggenerated
     */
    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_product_store.quantity
     *
     * @return the value of b_mall_product_store.quantity
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_product_store.quantity
     *
     * @param quantity the value for b_mall_product_store.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_product_store.safe_quantity
     *
     * @return the value of b_mall_product_store.safe_quantity
     *
     * @mbggenerated
     */
    public Integer getSafeQuantity() {
        return safeQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_product_store.safe_quantity
     *
     * @param safeQuantity the value for b_mall_product_store.safe_quantity
     *
     * @mbggenerated
     */
    public void setSafeQuantity(Integer safeQuantity) {
        this.safeQuantity = safeQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_product_store.online
     *
     * @return the value of b_mall_product_store.online
     *
     * @mbggenerated
     */
    public Boolean getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_product_store.online
     *
     * @param online the value for b_mall_product_store.online
     *
     * @mbggenerated
     */
    public void setOnline(Boolean online) {
        this.online = online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_mall_product_store.deleted
     *
     * @return the value of b_mall_product_store.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_mall_product_store.deleted
     *
     * @param deleted the value for b_mall_product_store.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}