package com.linjia.web.model;

public class MiddleCatagory {
    private Long id;
    
    private Integer largeCatagoryId;
    
    private boolean useStatus;
    
    private boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_middle_catagory.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_middle_catagory.sort_index
     *
     * @mbggenerated
     */
    private Integer sortIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_middle_catagory.id
     *
     * @return the value of b_middle_catagory.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_middle_catagory.id
     *
     * @param id the value for b_middle_catagory.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }


	public Integer getLargeCatagoryId() {
		return largeCatagoryId;
	}

	public void setLargeCatagoryId(Integer largeCatagoryId) {
		this.largeCatagoryId = largeCatagoryId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_middle_catagory.name
     *
     * @return the value of b_middle_catagory.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_middle_catagory.name
     *
     * @param name the value for b_middle_catagory.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_middle_catagory.sort_index
     *
     * @return the value of b_middle_catagory.sort_index
     *
     * @mbggenerated
     */
    public Integer getSortIndex() {
        return sortIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_middle_catagory.sort_index
     *
     * @param sortIndex the value for b_middle_catagory.sort_index
     *
     * @mbggenerated
     */
    public void setSortIndex(Integer sortIndex) {
        this.sortIndex = sortIndex;
    }

	public boolean isUseStatus() {
		return useStatus;
	}

	public void setUseStatus(boolean useStatus) {
		this.useStatus = useStatus;
	}

	public boolean isDeleted() {
		return deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}
    
    
}