package com.linjia.web.model;

public class OrderidGenerate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_orderid_generate.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_orderid_generate.id
     *
     * @return the value of b_orderid_generate.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_orderid_generate.id
     *
     * @param id the value for b_orderid_generate.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }
}