package com.linjia.web.model;

import java.math.BigDecimal;

public class OrderGroupProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order_group_product.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order_group_product.group_id
     *
     * @mbggenerated
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order_group_product.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order_group_product.p_code
     *
     * @mbggenerated
     */
    private String pCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order_group_product.p_name
     *
     * @mbggenerated
     */
    private String pName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order_group_product.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order_group_product.item_price
     *
     * @mbggenerated
     */
    private BigDecimal itemPrice;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order_group_product.item_price
     *
     * @mbggenerated
     */
    private Integer pSendType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_order_group_product.id
     *
     * @return the value of b_order_group_product.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order_group_product.id
     *
     * @param id the value for b_order_group_product.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_order_group_product.group_id
     *
     * @return the value of b_order_group_product.group_id
     *
     * @mbggenerated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order_group_product.group_id
     *
     * @param groupId the value for b_order_group_product.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_order_group_product.product_id
     *
     * @return the value of b_order_group_product.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order_group_product.product_id
     *
     * @param productId the value for b_order_group_product.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_order_group_product.p_code
     *
     * @return the value of b_order_group_product.p_code
     *
     * @mbggenerated
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order_group_product.p_code
     *
     * @param pCode the value for b_order_group_product.p_code
     *
     * @mbggenerated
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_order_group_product.p_name
     *
     * @return the value of b_order_group_product.p_name
     *
     * @mbggenerated
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order_group_product.p_name
     *
     * @param pName the value for b_order_group_product.p_name
     *
     * @mbggenerated
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_order_group_product.quantity
     *
     * @return the value of b_order_group_product.quantity
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order_group_product.quantity
     *
     * @param quantity the value for b_order_group_product.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_order_group_product.item_price
     *
     * @return the value of b_order_group_product.item_price
     *
     * @mbggenerated
     */
    public BigDecimal getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order_group_product.item_price
     *
     * @param itemPrice the value for b_order_group_product.item_price
     *
     * @mbggenerated
     */
    public void setItemPrice(BigDecimal itemPrice) {
        this.itemPrice = itemPrice;
    }

	public Integer getpSendType() {
		return pSendType;
	}

	public void setpSendType(Integer pSendType) {
		this.pSendType = pSendType;
	}
    
    
}