package com.linjia.web.model;

import java.util.Date;

public class Privilege {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_privilege.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_privilege.access_type
     *
     * @mbggenerated
     */
    private Boolean accessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_privilege.access_value
     *
     * @mbggenerated
     */
    private Integer accessValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_privilege.resource_id
     *
     * @mbggenerated
     */
    private Integer resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_privilege.operation
     *
     * @mbggenerated
     */
    private String operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_privilege.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_privilege.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_privilege.cre_date
     *
     * @mbggenerated
     */
    private Date creDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_privilege.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_privilege.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_privilege.updater
     *
     * @mbggenerated
     */
    private Integer updater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_privilege.id
     *
     * @return the value of m_privilege.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_privilege.id
     *
     * @param id the value for m_privilege.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_privilege.access_type
     *
     * @return the value of m_privilege.access_type
     *
     * @mbggenerated
     */
    public Boolean getAccessType() {
        return accessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_privilege.access_type
     *
     * @param accessType the value for m_privilege.access_type
     *
     * @mbggenerated
     */
    public void setAccessType(Boolean accessType) {
        this.accessType = accessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_privilege.access_value
     *
     * @return the value of m_privilege.access_value
     *
     * @mbggenerated
     */
    public Integer getAccessValue() {
        return accessValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_privilege.access_value
     *
     * @param accessValue the value for m_privilege.access_value
     *
     * @mbggenerated
     */
    public void setAccessValue(Integer accessValue) {
        this.accessValue = accessValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_privilege.resource_id
     *
     * @return the value of m_privilege.resource_id
     *
     * @mbggenerated
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_privilege.resource_id
     *
     * @param resourceId the value for m_privilege.resource_id
     *
     * @mbggenerated
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_privilege.operation
     *
     * @return the value of m_privilege.operation
     *
     * @mbggenerated
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_privilege.operation
     *
     * @param operation the value for m_privilege.operation
     *
     * @mbggenerated
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_privilege.comment
     *
     * @return the value of m_privilege.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_privilege.comment
     *
     * @param comment the value for m_privilege.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_privilege.deleted
     *
     * @return the value of m_privilege.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_privilege.deleted
     *
     * @param deleted the value for m_privilege.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_privilege.cre_date
     *
     * @return the value of m_privilege.cre_date
     *
     * @mbggenerated
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_privilege.cre_date
     *
     * @param creDate the value for m_privilege.cre_date
     *
     * @mbggenerated
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_privilege.creator
     *
     * @return the value of m_privilege.creator
     *
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_privilege.creator
     *
     * @param creator the value for m_privilege.creator
     *
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_privilege.update_date
     *
     * @return the value of m_privilege.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_privilege.update_date
     *
     * @param updateDate the value for m_privilege.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_privilege.updater
     *
     * @return the value of m_privilege.updater
     *
     * @mbggenerated
     */
    public Integer getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_privilege.updater
     *
     * @param updater the value for m_privilege.updater
     *
     * @mbggenerated
     */
    public void setUpdater(Integer updater) {
        this.updater = updater;
    }
}