package com.linjia.web.model;

import java.util.Date;

public class RolePrivilege {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role_privilege.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role_privilege.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role_privilege.privilege_id
     *
     * @mbggenerated
     */
    private Integer privilegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role_privilege.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role_privilege.cre_date
     *
     * @mbggenerated
     */
    private Date creDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role_privilege.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role_privilege.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_role_privilege.updater
     *
     * @mbggenerated
     */
    private Integer updater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role_privilege.id
     *
     * @return the value of m_role_privilege.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role_privilege.id
     *
     * @param id the value for m_role_privilege.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role_privilege.role_id
     *
     * @return the value of m_role_privilege.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role_privilege.role_id
     *
     * @param roleId the value for m_role_privilege.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role_privilege.privilege_id
     *
     * @return the value of m_role_privilege.privilege_id
     *
     * @mbggenerated
     */
    public Integer getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role_privilege.privilege_id
     *
     * @param privilegeId the value for m_role_privilege.privilege_id
     *
     * @mbggenerated
     */
    public void setPrivilegeId(Integer privilegeId) {
        this.privilegeId = privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role_privilege.deleted
     *
     * @return the value of m_role_privilege.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role_privilege.deleted
     *
     * @param deleted the value for m_role_privilege.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role_privilege.cre_date
     *
     * @return the value of m_role_privilege.cre_date
     *
     * @mbggenerated
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role_privilege.cre_date
     *
     * @param creDate the value for m_role_privilege.cre_date
     *
     * @mbggenerated
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role_privilege.creator
     *
     * @return the value of m_role_privilege.creator
     *
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role_privilege.creator
     *
     * @param creator the value for m_role_privilege.creator
     *
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role_privilege.update_date
     *
     * @return the value of m_role_privilege.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role_privilege.update_date
     *
     * @param updateDate the value for m_role_privilege.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_role_privilege.updater
     *
     * @return the value of m_role_privilege.updater
     *
     * @mbggenerated
     */
    public Integer getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_role_privilege.updater
     *
     * @param updater the value for m_role_privilege.updater
     *
     * @mbggenerated
     */
    public void setUpdater(Integer updater) {
        this.updater = updater;
    }
}