package com.linjia.web.model;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.web.multipart.MultipartFile;

public class ScoreProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.card_coupon_id
     *
     * @mbggenerated
     */
    private Long cardCouponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.image_path
     *
     * @mbggenerated
     */
    private String imagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.detail_path
     *
     * @mbggenerated
     */
    private String detailPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.exchange_type
     *
     * @mbggenerated
     */
    private Integer exchangeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.limit_quantity
     *
     * @mbggenerated
     */
    private Integer limitQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.sort_index
     *
     * @mbggenerated
     */
    private Integer sortIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.cre_date
     *
     * @mbggenerated
     */
    private Date creDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_score_product.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;
    
    private String detailText;


    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.card_coupon_id
     *
     * @return the value of b_score_product.card_coupon_id
     *
     * @mbggenerated
     */
    public Long getCardCouponId() {
        return cardCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.card_coupon_id
     *
     * @param cardCouponId the value for b_score_product.card_coupon_id
     *
     * @mbggenerated
     */
    public void setCardCouponId(Long cardCouponId) {
        this.cardCouponId = cardCouponId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.name
     *
     * @return the value of b_score_product.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.name
     *
     * @param name the value for b_score_product.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.price
     *
     * @return the value of b_score_product.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.price
     *
     * @param price the value for b_score_product.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.score
     *
     * @return the value of b_score_product.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.score
     *
     * @param score the value for b_score_product.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.image_path
     *
     * @return the value of b_score_product.image_path
     *
     * @mbggenerated
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.image_path
     *
     * @param imagePath the value for b_score_product.image_path
     *
     * @mbggenerated
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.detail_path
     *
     * @return the value of b_score_product.detail_path
     *
     * @mbggenerated
     */
    public String getDetailPath() {
        return detailPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.detail_path
     *
     * @param detailPath the value for b_score_product.detail_path
     *
     * @mbggenerated
     */
    public void setDetailPath(String detailPath) {
        this.detailPath = detailPath == null ? null : detailPath.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.quantity
     *
     * @return the value of b_score_product.quantity
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.quantity
     *
     * @param quantity the value for b_score_product.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.limit_quantity
     *
     * @return the value of b_score_product.limit_quantity
     *
     * @mbggenerated
     */
    public Integer getLimitQuantity() {
        return limitQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.limit_quantity
     *
     * @param limitQuantity the value for b_score_product.limit_quantity
     *
     * @mbggenerated
     */
    public void setLimitQuantity(Integer limitQuantity) {
        this.limitQuantity = limitQuantity;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.cre_date
     *
     * @return the value of b_score_product.cre_date
     *
     * @mbggenerated
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.cre_date
     *
     * @param creDate the value for b_score_product.cre_date
     *
     * @mbggenerated
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_score_product.deleted
     *
     * @return the value of b_score_product.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_score_product.deleted
     *
     * @param deleted the value for b_score_product.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getExchangeType() {
		return exchangeType;
	}

	public void setExchangeType(Integer exchangeType) {
		this.exchangeType = exchangeType;
	}

	public Integer getSortIndex() {
		return sortIndex;
	}

	public void setSortIndex(Integer sortIndex) {
		this.sortIndex = sortIndex;
	}
	
	private Boolean useStatus;
	
	private MultipartFile uploadImage;

	public Boolean getUseStatus() {
		return useStatus;
	}

	public void setUseStatus(Boolean useStatus) {
		this.useStatus = useStatus;
	}

	public String getDetailText() {
		return detailText;
	}

	public void setDetailText(String detailText) {
		this.detailText = detailText;
	}

	public MultipartFile getUploadImage() {
		return uploadImage;
	}

	public void setUploadImage(MultipartFile uploadImage) {
		this.uploadImage = uploadImage;
	}
	
	
    
    
}