package com.linjia.web.model;

import java.util.Date;

public class SecUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sec_user.id
     *
     * @mbggenerated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sec_user.id
     *
     * @mbggenerated
     */
    private Integer secRoleId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sec_user.id
     *
     * @mbggenerated
     */
    private Integer secUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sec_user.level
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sec_user.cre_date
     *
     * @mbggenerated
     */
    private Date creDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sec_user.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sec_user.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sec_user.updater
     *
     * @mbggenerated
     */
    private String updater;
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sec_user.id
     *
     * @return the value of m_sec_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sec_user.id
     *
     * @param id the value for m_sec_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sec_user.deleted
     *
     * @return the value of m_sec_user.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sec_user.deleted
     *
     * @param deleted the value for m_sec_user.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sec_user.cre_date
     *
     * @return the value of m_sec_user.cre_date
     *
     * @mbggenerated
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sec_user.cre_date
     *
     * @param creDate the value for m_sec_user.cre_date
     *
     * @mbggenerated
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sec_user.creator
     *
     * @return the value of m_sec_user.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sec_user.creator
     *
     * @param creator the value for m_sec_user.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sec_user.update_date
     *
     * @return the value of m_sec_user.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sec_user.update_date
     *
     * @param updateDate the value for m_sec_user.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sec_user.updater
     *
     * @return the value of m_sec_user.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sec_user.updater
     *
     * @param updater the value for m_sec_user.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

	public Integer getSecRoleId() {
		return secRoleId;
	}

	public void setSecRoleId(Integer secRoleId) {
		this.secRoleId = secRoleId;
	}

	public Integer getSecUserId() {
		return secUserId;
	}

	public void setSecUserId(Integer secUserId) {
		this.secUserId = secUserId;
	}

    
}