package com.linjia.web.model;

import java.math.BigDecimal;
import java.util.Date;

public class ShoppingCar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_shopping_car.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_shopping_car.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_shopping_car.p_code
     *
     * @mbggenerated
     */
    private String pCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_shopping_car.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_shopping_car.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_shopping_car.cre_date
     *
     * @mbggenerated
     */
    private Date creDate;
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_shopping_car.id
     *
     * @return the value of b_shopping_car.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_shopping_car.id
     *
     * @param id the value for b_shopping_car.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_shopping_car.product_id
     *
     * @return the value of b_shopping_car.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_shopping_car.product_id
     *
     * @param productId the value for b_shopping_car.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_shopping_car.p_code
     *
     * @return the value of b_shopping_car.p_code
     *
     * @mbggenerated
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_shopping_car.p_code
     *
     * @param pCode the value for b_shopping_car.p_code
     *
     * @mbggenerated
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_shopping_car.user_id
     *
     * @return the value of b_shopping_car.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_shopping_car.user_id
     *
     * @param userId the value for b_shopping_car.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_shopping_car.quantity
     *
     * @return the value of b_shopping_car.quantity
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_shopping_car.quantity
     *
     * @param quantity the value for b_shopping_car.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_shopping_car.cre_date
     *
     * @return the value of b_shopping_car.cre_date
     *
     * @mbggenerated
     */
    public Date getCreDate() {
        return creDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_shopping_car.cre_date
     *
     * @param creDate the value for b_shopping_car.cre_date
     *
     * @mbggenerated
     */
    public void setCreDate(Date creDate) {
        this.creDate = creDate;
    }
    
    /**
     * 购物车每条记录的价格
     */
    private BigDecimal itemPrice;
    
    /**
     * 购物车每条记录的状态
     * (0:正常；1：库存不足)
     */
    private int itemStatus;
    
    /**
     * 商品名
     */
    private String pName;
    
    /**
     * 商品发货类型：0及时送；1次日达
     */
    private int pSendType;
   

	public BigDecimal getItemPrice() {
		return itemPrice;
	}

	public void setItemPrice(BigDecimal itemPrice) {
		this.itemPrice = itemPrice;
	}

	public int getItemStatus() {
		return itemStatus;
	}

	public void setItemStatus(int itemStatus) {
		this.itemStatus = itemStatus;
	}

	public String getpName() {
		return pName;
	}

	public void setpName(String pName) {
		this.pName = pName;
	}

	public int getpSendType() {
		return pSendType;
	}

	public void setpSendType(int pSendType) {
		this.pSendType = pSendType;
	}

    
}