package com.linjia.web.model;

import java.math.BigDecimal;
import java.util.Date;

public class TailGoodsClear {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_tail_goods_clear.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_tail_goods_clear.type
	 *
	 * @mbggenerated
	 */
	private Integer type;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_tail_goods_clear.publish_start_time
	 *
	 * @mbggenerated
	 */
	private Date publishStartTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_tail_goods_clear.publish_end_time
	 *
	 * @mbggenerated
	 */
	private Date publishEndTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_tail_goods_clear.product_id
	 *
	 * @mbggenerated
	 */
	private Integer productId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_tail_goods_clear.p_code
	 *
	 * @mbggenerated
	 */
	private String pCode;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_tail_goods_clear.p_name
	 *
	 * @mbggenerated
	 */
	private String pName;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_tail_goods_clear.market_price
	 *
	 * @mbggenerated
	 */
	private BigDecimal marketPrice;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_tail_goods_clear.clear_price
	 *
	 * @mbggenerated
	 */
	private BigDecimal clearPrice;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_tail_goods_clear.quantity
	 *
	 * @mbggenerated
	 */
	private Integer quantity;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_tail_goods_clear.p_image_path
	 *
	 * @mbggenerated
	 */
	private String pImagePath;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_tail_goods_clear.search_condition
	 *
	 * @mbggenerated
	 */
	private Integer searchCondition;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_tail_goods_clear.search_time
	 *
	 * @mbggenerated
	 */
	private Date searchTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_tail_goods_clear.mall_support_type
	 *
	 * @mbggenerated
	 */
	private Integer mallSupportType;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_tail_goods_clear.mall_id
	 *
	 * @mbggenerated
	 */
	private Integer mallId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_tail_goods_clear.mall_code
	 *
	 * @mbggenerated
	 */
	private String mallCode;
	private String mallNames;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_tail_goods_clear.sort_index
	 *
	 * @mbggenerated
	 */
	private Integer sortIndex;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_tail_goods_clear.activity_status
	 *
	 * @mbggenerated
	 */
	private Integer activityStatus;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column b_tail_goods_clear.use_status
	 *
	 * @mbggenerated
	 */
	private Boolean useStatus;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_tail_goods_clear.id
	 *
	 * @return the value of b_tail_goods_clear.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_tail_goods_clear.id
	 *
	 * @param id the value for b_tail_goods_clear.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_tail_goods_clear.publish_start_time
	 *
	 * @return the value of b_tail_goods_clear.publish_start_time
	 *
	 * @mbggenerated
	 */
	public Date getPublishStartTime() {
		return publishStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_tail_goods_clear.publish_start_time
	 *
	 * @param publishStartTime the value for b_tail_goods_clear.publish_start_time
	 *
	 * @mbggenerated
	 */
	public void setPublishStartTime(Date publishStartTime) {
		this.publishStartTime = publishStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_tail_goods_clear.publish_end_time
	 *
	 * @return the value of b_tail_goods_clear.publish_end_time
	 *
	 * @mbggenerated
	 */
	public Date getPublishEndTime() {
		return publishEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_tail_goods_clear.publish_end_time
	 *
	 * @param publishEndTime the value for b_tail_goods_clear.publish_end_time
	 *
	 * @mbggenerated
	 */
	public void setPublishEndTime(Date publishEndTime) {
		this.publishEndTime = publishEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_tail_goods_clear.product_id
	 *
	 * @return the value of b_tail_goods_clear.product_id
	 *
	 * @mbggenerated
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_tail_goods_clear.product_id
	 *
	 * @param productId the value for b_tail_goods_clear.product_id
	 *
	 * @mbggenerated
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_tail_goods_clear.p_code
	 *
	 * @return the value of b_tail_goods_clear.p_code
	 *
	 * @mbggenerated
	 */
	public String getpCode() {
		return pCode;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_tail_goods_clear.p_code
	 *
	 * @param pCode the value for b_tail_goods_clear.p_code
	 *
	 * @mbggenerated
	 */
	public void setpCode(String pCode) {
		this.pCode = pCode == null ? null : pCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_tail_goods_clear.p_name
	 *
	 * @return the value of b_tail_goods_clear.p_name
	 *
	 * @mbggenerated
	 */
	public String getpName() {
		return pName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_tail_goods_clear.p_name
	 *
	 * @param pName the value for b_tail_goods_clear.p_name
	 *
	 * @mbggenerated
	 */
	public void setpName(String pName) {
		this.pName = pName == null ? null : pName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_tail_goods_clear.market_price
	 *
	 * @return the value of b_tail_goods_clear.market_price
	 *
	 * @mbggenerated
	 */
	public BigDecimal getMarketPrice() {
		return marketPrice;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_tail_goods_clear.market_price
	 *
	 * @param marketPrice the value for b_tail_goods_clear.market_price
	 *
	 * @mbggenerated
	 */
	public void setMarketPrice(BigDecimal marketPrice) {
		this.marketPrice = marketPrice;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_tail_goods_clear.clear_price
	 *
	 * @return the value of b_tail_goods_clear.clear_price
	 *
	 * @mbggenerated
	 */
	public BigDecimal getClearPrice() {
		return clearPrice;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_tail_goods_clear.clear_price
	 *
	 * @param clearPrice the value for b_tail_goods_clear.clear_price
	 *
	 * @mbggenerated
	 */
	public void setClearPrice(BigDecimal clearPrice) {
		this.clearPrice = clearPrice;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_tail_goods_clear.quantity
	 *
	 * @return the value of b_tail_goods_clear.quantity
	 *
	 * @mbggenerated
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_tail_goods_clear.quantity
	 *
	 * @param quantity the value for b_tail_goods_clear.quantity
	 *
	 * @mbggenerated
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_tail_goods_clear.p_image_path
	 *
	 * @return the value of b_tail_goods_clear.p_image_path
	 *
	 * @mbggenerated
	 */
	public String getpImagePath() {
		return pImagePath;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_tail_goods_clear.p_image_path
	 *
	 * @param pImagePath the value for b_tail_goods_clear.p_image_path
	 *
	 * @mbggenerated
	 */
	public void setpImagePath(String pImagePath) {
		this.pImagePath = pImagePath == null ? null : pImagePath.trim();
	}

	public Integer getSearchCondition() {
		return searchCondition;
	}

	public void setSearchCondition(Integer searchCondition) {
		this.searchCondition = searchCondition;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_tail_goods_clear.search_time
	 *
	 * @return the value of b_tail_goods_clear.search_time
	 *
	 * @mbggenerated
	 */
	public Date getSearchTime() {
		return searchTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_tail_goods_clear.search_time
	 *
	 * @param searchTime the value for b_tail_goods_clear.search_time
	 *
	 * @mbggenerated
	 */
	public void setSearchTime(Date searchTime) {
		this.searchTime = searchTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_tail_goods_clear.mall_id
	 *
	 * @return the value of b_tail_goods_clear.mall_id
	 *
	 * @mbggenerated
	 */
	public Integer getMallId() {
		return mallId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_tail_goods_clear.mall_id
	 *
	 * @param mallId the value for b_tail_goods_clear.mall_id
	 *
	 * @mbggenerated
	 */
	public void setMallId(Integer mallId) {
		this.mallId = mallId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_tail_goods_clear.mall_code
	 *
	 * @return the value of b_tail_goods_clear.mall_code
	 *
	 * @mbggenerated
	 */
	public String getMallCode() {
		return mallCode;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_tail_goods_clear.mall_code
	 *
	 * @param mallCode the value for b_tail_goods_clear.mall_code
	 *
	 * @mbggenerated
	 */
	public void setMallCode(String mallCode) {
		this.mallCode = mallCode == null ? null : mallCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_tail_goods_clear.sort_index
	 *
	 * @return the value of b_tail_goods_clear.sort_index
	 *
	 * @mbggenerated
	 */
	public Integer getSortIndex() {
		return sortIndex;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_tail_goods_clear.sort_index
	 *
	 * @param sortIndex the value for b_tail_goods_clear.sort_index
	 *
	 * @mbggenerated
	 */
	public void setSortIndex(Integer sortIndex) {
		this.sortIndex = sortIndex;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column b_tail_goods_clear.use_status
	 *
	 * @return the value of b_tail_goods_clear.use_status
	 *
	 * @mbggenerated
	 */
	public Boolean getUseStatus() {
		return useStatus;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column b_tail_goods_clear.use_status
	 *
	 * @param useStatus the value for b_tail_goods_clear.use_status
	 *
	 * @mbggenerated
	 */
	public void setUseStatus(Boolean useStatus) {
		this.useStatus = useStatus;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getMallSupportType() {
		return mallSupportType;
	}

	public void setMallSupportType(Integer mallSupportType) {
		this.mallSupportType = mallSupportType;
	}

	public Integer getActivityStatus() {
		return activityStatus;
	}

	public void setActivityStatus(Integer activityStatus) {
		this.activityStatus = activityStatus;
	}

	private Date creDate;
	private Date updateDate;

	public Date getCreDate() {
		return creDate;
	}

	public void setCreDate(Date creDate) {
		this.creDate = creDate;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	private String publishStartTimeStr;
	private String publishEndTimeStr;
	private String searchTimeStr;
	private String mall_codes;

	/** 商品发货类型：0及时送；1次日达* */
	private Integer pSendType;

	public String getPublishStartTimeStr() {
		return publishStartTimeStr;
	}

	public void setPublishStartTimeStr(String publishStartTimeStr) {
		this.publishStartTimeStr = publishStartTimeStr;
	}

	public String getPublishEndTimeStr() {
		return publishEndTimeStr;
	}

	public void setPublishEndTimeStr(String publishEndTimeStr) {
		this.publishEndTimeStr = publishEndTimeStr;
	}

	public String getSearchTimeStr() {
		return searchTimeStr;
	}

	public void setSearchTimeStr(String searchTimeStr) {
		this.searchTimeStr = searchTimeStr;
	}

	public Integer getpSendType() {
		return pSendType;
	}

	public void setpSendType(Integer pSendType) {
		this.pSendType = pSendType;
	}

	public String getMall_codes() {
		return mall_codes;
	}

	public void setMall_codes(String mall_codes) {
		this.mall_codes = mall_codes;
	}

	public String getMallNames() {
		return mallNames;
	}

	public void setMallNames(String mallNames) {
		this.mallNames = mallNames;
	}

}